if POS_ABLATION:
  dir_script, row = script_generation(grid_label=LABEL_GRID, 
                                    init_param=params_dozat,#params_dozat,#params_strong,#params_dozat,
                                    warmup=test_before_run, test_before_run=test_before_run,
                                    dir_grid=dir_grid, environment=environment, dir_log=log,
                                    stable_decoding_state_ls=[0],
                                    word_decoding_ls=[0],
                                    epochs=epochs if not (test_before_run or warmup) else 1,
                                    batch_size_ls=[30,50,70,90],
                                    word_embed_ls=[1],
                                    dir_sent_encoder_ls=[2], dir_word_encoder_ls=[1],
                                    n_layers_sent_cell_ls=[2], n_layers_word_encoder_ls=[1],
                                    lr_ls=[0.0015,0.001, 0.0005],
                                    word_embed_init_ls=[None],
                                    teacher_force_ls=[1],
                                    word_recurrent_cell_encoder_ls=["LSTM"],
                                    dropout_word_encoder_cell_ls=[0.],
                                    proportion_pred_train_ls=[None],
                                    shared_context_ls=["sent"],
                                    word_embedding_projected_dim_ls=[125],
                                    char_level_embedding_projection_dim_ls=[125],
                                    mode_word_encoding_ls=["sum"],
                                    tasks_ls=[["pos"]],
                                    char_src_attention_ls=[0],
                                    unrolling_word_ls=[1],
                                    scale_ls=[1],
                                    attention_tagging_ls=[1],
                                    overall_report_dir=dir_grid, overall_label=LABEL_GRID,
                                    description_comment=description_comment,
                                    train_path=train_path, dev_path=dev_path,
                                    test_paths=[TEST, EWT_DEV, EWT_TEST, EN_LINES_EWT_TRAIN],
                                    gpu_mode="random",
                                    gpus_ls=gpu_ls,
                                    scoring_func="exact_match",
                                    dropout_input_ls=[0., 0.1, 0.2, 0.3, 0.4],
                                    multi_task_loss_ponderation_ls=[{"pos": 1, "normalize": 0, "norm_not_norm":0}],
                                    write_to_dir=RUN_SCRIPTS_DIR)