

DEFAULT_LR = 0.001
DEFAULT_WORD_EMBED_INIT = None
DEFAULT_SHARED_CONTEXT = "all"
DEFAULT_DIR_WORD_ENCODER = 2
DEFAULT_CHAR_SRC_ATTENTION = 1
DEFAULT_DIR_SENT_ENCODER = 2
DEFAULT_CLIPPING = 1
DEFAULT_WORD_UNROLLING = 1
DEFAULT_TEACHER_FORCE = 1
DEFAULT_WORD_DECODING = 0
DEFAULT_STABLE_DECODING = 0
DEFAULT_WORD_EMBEDDING_PROJECTED = None
DEFAULT_PROPORTION_PRED_TRAIN = None
DEFAULT_LAYERS_SENT_CELL = 1
DEFAULT_WORD_EMBED = 1
DEFAULT_DROPOUT_WORD_ENCODER_CELL = 0.0
DEFAULT_ATTENTION_TAGGING = 0
DEFAULT_LAYER_WORD_ENCODER = 1
DEFAULT_MODE_WORD_ENCODING = "cat"
DEFAULT_CHAR_LEVEL_EMBEDDING_PROJECTION = 0
DEFAULT_WORD_RECURRENT_CELL = "LSTM"
DEFAULT_TASKS = ["normalize"]
